<?php

return [
    'rightsToRemoveForNotSuperAdmins' => [
        "agent" => 0,
        "appliance" => 0,
        "backup" => 0,
        "bookmark_public" => 0,
        "budget" => 0,
        "cable_management" => 0,
        "calendar" => 0,
        "certificate" => 0,
        "change" => 0,
        "changevalidation" => 0,
        "cluster" => 0,
        "computer" => 0,
        "config" => 0,
        "database" => 0,
        "datacenter" => 0,
        "document" => 0,
        "domain" => 0,
        "dropdown" => 0,
        "entity" => 0,
        "externalevent" => 0,
        "followup" => 0,
        "global_validation" => 0,
        "group" => 0,
        "infocom" => 0,
        "internet" => 0,
        "inventory" => 0,
        "itilcategory" => 0,
        "itilfollowuptemplate" => 0,
        "itiltemplate" => 0,
        "knowbase" => 0,
        "knowbasecategory" => 0,
        "license" => 0,
        "line" => 0,
        "lineoperator" => 0,
        "link" => 0,
        "location" => 0,
        "locked_field" => 0,
        "logs" => 0,
        "monitor" => 0,
        "networking" => 0,
        "notification" => 0,
        "password_update" => 0,
        "pendingreason" => 0,
        "peripheral" => 0,
        "personalization" => 0,
        "phone" => 0,
        "problem" => 0,
        "profile" => 0,
        "project" => 0,
        "projecttask" => 0,
        "queuednotification" => 0,
        "recurrentchange" => 0,
        "refusedequipment" => 0,
        "reminder_public" => 0,
        "reports" => 0,
        "reservation" => 0,
        "rssfeed_public" => 0,
        "rule_asset" => 0,
        "rule_dictionnary_dropdown" => 0,
        "rule_dictionnary_printer" => 0,
        "rule_dictionnary_software" => 0,
        "rule_import" => 0,
        "rule_ldap" => 0,
        "rule_location" => 0,
        "rule_mailcollector" => 0,
        "rule_softwarecategories" => 0,
        "rule_ticket" => 0,
        "search_config" => 0,
        "show_group_hardware" => 0,
        "slm" => 0,
        "snmpcredential" => 0,
        "software" => 0,
        "solutiontemplate" => 0,
        "state" => 0,
        "task" => 0,
        "taskcategory" => 0,
        "ticketcost" => 0,
        "ticketrecurrent" => 0,
        "ticketvalidation" => 0,
        "transfer" => 0,
        "typedoc" => 0,
        "unmanaged" => 0,
        "user" => 0,
    ],
    'defaultValues' => [
        'client' => [
            'ticket' => 127,
            'printer' => 127,
            'cartridge' => 127,
        ],
        'superclient' => [
            'ticket' => 127,
            'printer' => 127,
            'cartridge' => 127,
        ],
        'super-admin' => [
            'computer' => 0,
            'monitor' => 0,
            'software' => 0,
            'networking' => 0,
            'peripheral' => 0,
            'consumable' => 0,
            'phone' => 0,
            'datacenter' => 0,
            'unmanaged' => 0,
            'cable_management' => 0,
            'device' => 0,
        ],
        'admin' => [
            'cartridge' => 127,
            'consumable' => 127,
            'contact_enterprise' => 127,
            'contract' => 127,
            'device' => 23,
            'devicesimcard_pinpuk' => 3,
            'location' => 23,
            'planning' => 3073,
            'printer' => 127,
            'reminder' => 127,
            'state' => 23,
            'ticket' => 261151,
        ],
        'tehnician' => [
            'cartridge' => 127,
            'consumable' => 127,
            'contact_enterprise' => 127,
            'contract' => 127,
            'device' => 23,
            'devicesimcard_pinpuk' => 3,
            'location' => 23,
            'planning' => 3073,
            'printer' => 127,
            'reminder' => 127,
            'state' => 23,
            'ticket' => 261151,
        ],
    ],
    'customFieldsRightsSettings' => [
        'profilesWithFullAccess' => [
            'super-admin',
            'admin',
            'tehnician',
            'subtehnician',
            'superclient',
            'client',
        ],
    ]
];
