create table if not exists `glpi_plugin_iservice_configs`
(
    `id`    int unsigned not null auto_increment,
    `name`  varchar(150) not null,
    `value` text,
    primary key (`id`),
    index `name` (`name`)
);

insert into `glpi_plugin_iservice_configs` (`name`, `value`)
values ('version', '0');

create table if not exists `glpi_plugin_iservice_importmappings`
(
    `id`       int unsigned not null auto_increment,
    `itemtype` varchar(255) not null,
    `items_id` int unsigned not null,
    `old_id`   int unsigned not null,
    primary key (`id`),
    unique index `item` (`itemtype`, `items_id`),
    unique index `old_item` (`itemtype`, `old_id`)
);

create table if not exists `hmarfa_facrind` (
    `tip` varchar(5) null default null,
    `nrfac` varchar(6) null default null,
    `grupa` varchar(6) null default null,
    `codmat` varchar(15) null default null,
    `gest` varchar(4) null default null,
    `nrtran` varchar(6) null default null,
    `cent` varchar(4) null default null,
    `centlot` varchar(11) null default null,
    `descr` varchar(125) null default null,
    `obs1` varchar(30) null default null,
    `cant` double null default null,
    `pucont` double null default null,
    `puini` double null default null,
    `puliv` double null default null,
    `puvin` double null default null,
    `pudol` double null default null,
    `vbaza` double null default null,
    `tvan` int(11) null default null,
    `icm` int(11) null default null,
    `tvapoz` varchar(3) null default null,
    `vtva` double null default null,
    `acc` int(11) null default null,
    `nb_upd` int(11) null default null,
    index `nrtran` (`nrtran`),
    index `codmat` (`codmat`)
);

create table if not exists `hmarfa_facturi` (
    `nrjur` varchar(5) null default null,
    `nrfac` varchar(6) not null,
    `nrrs` varchar(15) null default null,
    `nrsec` varchar(6) null default null,
    `factva` enum('f','t') null default null,
    `datafac` date null default null,
    `dscad` date null default null,
    `dscadtva` date null default null,
    `tipbenef` varchar(1) null default null,
    `codbenef` varchar(7) null default null,
    `tvaibenef` varchar(1) null default null,
    `cif` varchar(15) null default null,
    `stare` varchar(3) null default null,
    `nrcmd` varchar(12) null default null,
    `centdoc` varchar(11) null default null,
    `deleg` varchar(5) null default null,
    `tip` varchar(5) null default null,
    `model` varchar(1) null default null,
    `valvin` double null default null,
    `valliv` double null default null,
    `dolliv` double null default null,
    `valinc` double null default null,
    `dolinc` double null default null,
    `valrev` double null default null,
    `valrev2` double null default null,
    `valprv2` double null default null,
    `moneda` varchar(3) null default null,
    `curs` double null default null,
    `valpla` double null default null,
    `numerar` double null default null,
    `card` double null default null,
    `tichet` double null default null,
    `dolpla` double null default null,
    `valinr` double null default null,
    `valicm` double null default null,
    `tvai` double null default null,
    `valacc` double null default null,
    `cont` varchar(11) null default null,
    `txtlib` text null default null,
    `codl` varchar(10) null default null,
    `optva` varchar(5) null default null,
    `nb_upd` int(11) null default null,
    primary key (`nrfac`),
    index `nrfac` (`nrfac`),
    index `codbenef` (`codbenef`)
);

create table if not exists `hmarfa_firme` (
    `cod` varchar(7) not null,
    `initiale` varchar(30) null default null,
    `tip` varchar(10) null default null,
    `denum` varchar(50) null default null,
    `cod1` varchar(15) null default null,
    `cod2` varchar(15) null default null,
    `contdb` varchar(11) null default null,
    `contcr` varchar(11) null default null,
    `codpostal` varchar(7) null default null,
    `localitate` varchar(20) null default null,
    `adrs1` varchar(40) null default null,
    `adrs2` varchar(40) null default null,
    `adrp1` varchar(40) null default null,
    `adrp2` varchar(40) null default null,
    `tel1` varchar(15) null default null,
    `tel2` varchar(15) null default null,
    `fax` varchar(15) null default null,
    `telex` varchar(40) null default null,
    `web` varchar(40) null default null,
    `banca` varchar(35) null default null,
    `cont` varchar(29) null default null,
    `obs` text null default null,
    `nb_upd` int(11) null default null,
    `zile_scad` int(11) null default null,
    `tip_pret` varchar(1) null default null,
    `credit_lim` int(11) null default null,
    primary key (`cod`)
);

create table if not exists `hmarfa_gestiuni` (
    `cod` varchar(4) null default null,
    `denum` varchar(30) null default null,
    `descr` varchar(100) null default null,
    `nb_upd` int(11) null default null
);

create table if not exists `hmarfa_incpla` (
    `nrjur` varchar(5) null default null,
    `nrfila` varchar(6) null default null,
    `data` date null default null,
    `tipip` varchar(1) null default null,
    `tipdoc` varchar(5) null default null,
    `model` varchar(1) null default null,
    `nrdoc` varchar(20) null default null,
    `datadoc` date null default null,
    `nrfac` varchar(6) null default null,
    `tipfact` varchar(1) null default null,
    `centdoc` varchar(11) null default null,
    `obs1fac` varchar(40) null default null,
    `obs2fac` varchar(40) null default null,
    `tippart` varchar(1) null default null,
    `partener` varchar(7) null default null,
    `obspart` varchar(40) null default null,
    `sumaval` double null default null,
    `moneda` varchar(3) null default null,
    `suma` double null default null,
    `sumafac` double null default null,
    `sumarev` double null default null,
    `sumaprv2` double null default null,
    `sumarev2` double null default null,
    `tvaip` double null default null,
    `contcr` varchar(11) null default null,
    `stare` varchar(3) null default null,
    `codl` varchar(10) null default null,
    `nb_upd` int(11) null default null,
    index `partener` (`partener`)
);

create table if not exists `hmarfa_lotm` (
    `nrtran` varchar(6) null default null,
    `codmat` varchar(15) null default null,
    `gest` varchar(4) null default null,
    `centlot` varchar(11) null default null,
    `umamb` varchar(3) null default null,
    `fctcv` double null default null,
    `tip` varchar(1) null default null,
    `tipgest` varchar(2) null default null,
    `metstoc` varchar(4) null default null,
    `grupa` varchar(6) null default null,
    `pachdol` double null default null,
    `moneda` varchar(3) null default null,
    `pach` double null default null,
    `pinvama` double null default null,
    `pvama` double null default null,
    `pchelt` double null default null,
    `paccr` double null default null,
    `ptaxe` double null default null,
    `pini` double null default null,
    `pinr` double null default null,
    `pliv` double null default null,
    `pvin` double null default null,
    `pcont` double null default null,
    `cont` varchar(11) null default null,
    `stoci` double null default null,
    `iesiri` double null default null,
    `cist` double null default null,
    `dataexp` date null default null,
    `obs` varchar(20) null default null,
    `nb_upd` int(11) null default null,
    index `nrtran` (`nrtran`),
    index `codmat` (`codmat`)
);

create table if not exists `hmarfa_nommarfa` (
    `cod` varchar(15) not null,
    `denum` varchar(30) null default null,
    `descr` varchar(60) null default null,
    `um` varchar(3) null default null,
    `masan` double null default null,
    `grupa` varchar(6) null default null,
    `cod_ech` varchar(5) null default null,
    `vama` double null default null,
    `vamapoz` varchar(10) null default null,
    `tva` int(11) null default null,
    `tvapoz` varchar(6) null default null,
    `acz` int(11) null default null,
    `aczpoz` varchar(4) null default null,
    `icm` int(11) null default null,
    `icmpoz` varchar(6) null default null,
    `acc` int(11) null default null,
    `accpoz` varchar(4) null default null,
    `prod_txi` varchar(13) null default null,
    `prod_tx0` varchar(13) null default null,
    `caen_act` varchar(8) null default null,
    `pvinv` double null default null,
    `moneda` varchar(3) null default null,
    `pvin` double null default null,
    `pvina` double null default null,
    `nb_upd` int(11) null default null,
    `cod_produc` varchar(20) null default null,
    `p_preturi` enum('f','t') null default null,
    `p_pret1` double null default null,
    `p_pret2` double null default null,
    `p_pret3` double null default null,
    primary key (`cod`)
);

create table if not exists `hmarfa_tran` (
    `nrjur` varchar(5) null default null,
    `nrtran` varchar(6) not null,
    `gest` varchar(4) null default null,
    `tipdcm` varchar(5) null default null,
    `model` varchar(1) null default null,
    `dataint` date null default null,
    `nrcmd` varchar(12) null default null,
    `tipfurn` varchar(1) null default null,
    `furnizor` varchar(7) null default null,
    `nrdoc` varchar(20) null default null,
    `datadoc` date null default null,
    `fdscad` date null default null,
    `valdol` double null default null,
    `pladol` double null default null,
    `moneda` varchar(3) null default null,
    `val` double null default null,
    `valrev` double null default null,
    `tva` double null default null,
    `pla` double null default null,
    `cont` varchar(11) null default null,
    `furvama` varchar(7) null default null,
    `nrvama` varchar(20) null default null,
    `datavama` date null default null,
    `vdscad` date null default null,
    `valvama` double null default null,
    `txvama` double null default null,
    `tvavama` double null default null,
    `acc` double null default null,
    `plavama` double null default null,
    `contvama` varchar(11) null default null,
    `furchel` varchar(7) null default null,
    `nrchel` varchar(20) null default null,
    `datachel` date null default null,
    `cdscad` date null default null,
    `valchel` double null default null,
    `tvachel` double null default null,
    `plachel` double null default null,
    `contchel` varchar(11) null default null,
    `stare` varchar(3) null default null,
    `optva` varchar(5) null default null,
    primary key (`nrtran`),
    index `hmarfa_tran_dataint_idx` (`dataint`)
);

create or replace view hmarfa_total_facturi as
select
    `f`.`codbenef` as `codbenef`,
    count(`f`.`nrfac`) as `numar_facturi`,
    sum(`f`.`valinc` - `f`.`valpla`) as `total_facturi`
from `hmarfa_facturi` `f`
where `f`.`tip` like 'tf%' and `f`.`valinc` - `f`.`valpla` > 0
group by `f`.`codbenef`;
